# Generated by Django 5.2.11 on 2026-06-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Canal",
            fields=[
                (
                    "basehydrofacility_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basehydrofacility",
                    ),
                ),
                (
                    "capacity",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Пропускная способность, м3/с",
                    ),
                ),
                (
                    "total_length",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Всего протяжённость, км"
                    ),
                ),
                (
                    "earth_length",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Земляное русло, км"
                    ),
                ),
                (
                    "lined_length",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Облицованное русло, км"
                    ),
                ),
                (
                    "area_regular",
                    models.FloatField(
                        default=0.0,
                        verbose_name="Подвешенная площадь: регулярное орошение, га",
                    ),
                ),
                (
                    "area_liman",
                    models.FloatField(
                        default=0.0, verbose_name="Лиманное орошение, га"
                    ),
                ),
                (
                    "area_flooded",
                    models.FloatField(default=0.0, verbose_name="Обводненное, га"),
                ),
                (
                    "bottom_width",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ширина по дну, м"
                    ),
                ),
                (
                    "top_width",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ширина по верху, м"
                    ),
                ),
                (
                    "depth",
                    models.FloatField(blank=True, null=True, verbose_name="Глубина, м"),
                ),
            ],
            bases=("core.basehydrofacility",),
        ),
        migrations.CreateModel(
            name="DamsAndDykes",
            fields=[
                (
                    "basehydrofacility_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basehydrofacility",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Материал сооружения (Земляная, бетонная, каменно-набросная)",
                    ),
                ),
                (
                    "crest_length",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Длина по гребню, м"
                    ),
                ),
                (
                    "max_height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальная высота сооружения, м",
                    ),
                ),
                (
                    "reservoir_volume",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Объем удерживаемого водохранилища, млн м3",
                    ),
                ),
                (
                    "is_declared_dangerous",
                    models.BooleanField(
                        default=False,
                        verbose_name="Относится ли к декларируемым аварийным объектам",
                    ),
                ),
            ],
            bases=("core.basehydrofacility",),
        ),
        migrations.CreateModel(
            name="PumpingStation",
            fields=[
                (
                    "basehydrofacility_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basehydrofacility",
                    ),
                ),
                (
                    "pumps_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество установленных насосов"
                    ),
                ),
                (
                    "installed_power",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Суммарная мощность электродвигателей, кВт",
                    ),
                ),
                (
                    "current_consumption",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Фактический расход энергии"
                    ),
                ),
                (
                    "head_pressure",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Напор насосной станции, метры водного столба",
                    ),
                ),
            ],
            bases=("core.basehydrofacility",),
        ),
        migrations.CreateModel(
            name="Sluice",
            fields=[
                (
                    "basehydrofacility_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basehydrofacility",
                    ),
                ),
                (
                    "gates_count",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество затворов/сооружений",
                    ),
                ),
                (
                    "gate_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Тип затвора",
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Привод затвора (электрический, механический, ручной)",
                    ),
                ),
                (
                    "max_discharge",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальный сброс воды, м3/с",
                    ),
                ),
            ],
            bases=("core.basehydrofacility",),
        ),
        migrations.CreateModel(
            name="WaterIntake",
            fields=[
                (
                    "basehydrofacility_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basehydrofacility",
                    ),
                ),
                (
                    "intake_type",
                    models.CharField(
                        max_length=100,
                        verbose_name="Тип водозабора (Береговой, русловой, плавучий)",
                    ),
                ),
                (
                    "is_gravity",
                    models.BooleanField(
                        default=True,
                        verbose_name="Самотечный (True) или механический (False)",
                    ),
                ),
                (
                    "fish_protection",
                    models.BooleanField(
                        default=False, verbose_name="Наличие рыбозащитных устройств"
                    ),
                ),
                (
                    "max_volume_clean",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Проектный объем забора воды",
                    ),
                ),
            ],
            bases=("core.basehydrofacility",),
        ),
    ]
