# Generated by Django 5.2.11 on 2026-06-25 15:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseHydroFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("canal", "Канал"),
                            ("post", "Гидропост"),
                            ("sluice", "Шлюз"),
                            ("intake", "Водозабор"),
                            ("pumping", "Насосная станция"),
                            ("dam_dyke", "Плотина/Дамба"),
                        ],
                        max_length=30,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "uid",
                    models.FloatField(
                        blank=True, null=True, verbose_name="№ по реестру"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "water_source",
                    models.CharField(max_length=255, verbose_name="Водоисточник"),
                ),
                (
                    "district",
                    models.CharField(
                        max_length=255, verbose_name="Название обслуживаемого района"
                    ),
                ),
                (
                    "rural_district",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Сельский округ",
                    ),
                ),
                (
                    "cadastral_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Кадастровый номер",
                    ),
                ),
                (
                    "state_act",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Гос Акт"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Координаты объекта",
                    ),
                ),
                (
                    "year_built",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год ввода в эксплуатацию"
                    ),
                ),
                (
                    "year_balanced",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год принятия на баланс РС"
                    ),
                ),
                (
                    "wear_percentage",
                    models.FloatField(default=0.0, verbose_name="Процент износа"),
                ),
                (
                    "technical_condition",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Техническое состояние",
                    ),
                ),
                (
                    "efficiency_project",
                    models.FloatField(
                        blank=True, null=True, verbose_name="КПД проектный"
                    ),
                ),
                (
                    "efficiency_fact",
                    models.FloatField(
                        blank=True, null=True, verbose_name="КПД фактический"
                    ),
                ),
                (
                    "is_emergency_prone",
                    models.BooleanField(
                        default=False, verbose_name="Флаг повышенной аварийности"
                    ),
                ),
            ],
        ),
    ]
