# Generated by Django 5.2.15 on 2026-06-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionlog',
            name='inspection_type',
            field=models.CharField(choices=[('planned', 'Плановый'), ('post_accident', 'После аварии'), ('post_repair', 'После ремонта'), ('commissioning', 'При вводе в эксплуатацию')], default='planned', max_length=20, verbose_name='Тип триггерного события осмотра'),
        ),
    ]
