# Generated by Django 5.2.15 on 2026-06-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_inspectionlog_inspection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionlog',
            name='crack_width',
            field=models.FloatField(blank=True, null=True, verbose_name='Раскрытие трещины, мм'),
        ),
        migrations.AddField(
            model_name='inspectionlog',
            name='deformation_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Измеренное смещение/просадка, мм'),
        ),
        migrations.AddField(
            model_name='inspectionlog',
            name='filtration_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Измеренный расход фильтрации, л/с (для сравнения с K1/K2)'),
        ),
    ]
