# Generated by Django 5.2.15 on 2026-06-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basehydrofacility',
            name='design_service_life',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расчётный срок службы, лет (по классу, п. 5.3.7)'),
        ),
        migrations.AddField(
            model_name='basehydrofacility',
            name='is_seasonal_risk',
            field=models.BooleanField(default=False, verbose_name='Чувствителен к паводку/ледоставу (учащение осмотров в сезон)'),
        ),
        migrations.AddField(
            model_name='basehydrofacility',
            name='safety_class',
            field=models.IntegerField(blank=True, choices=[(1, 'I класс'), (2, 'II класс'), (3, 'III класс'), (4, 'IV класс')], null=True, verbose_name='Класс ГТС (по прил. 2 СНиП РК 3.04-01-2008)'),
        ),
    ]
