# Generated by Django 5.2.15 on 2026-06-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_basehydrofacility_design_service_life_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basehydrofacility',
            name='has_pressure_front',
            field=models.BooleanField(default=False, verbose_name='Участвует в создании напорного фронта (СНиП 5.1.3, 5.3.7)'),
        ),
    ]
