# Generated by Django 5.2.11 on 2026-06-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HydroPost",
            fields=[
                (
                    "basehydrofacility_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basehydrofacility",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        max_length=50,
                        verbose_name="Тип поста (Автоматический / Ручной)",
                    ),
                ),
                (
                    "equipment_installed",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Модель датчика/эхолота",
                    ),
                ),
                (
                    "current_water_level",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Текущий уровень воды, см"
                    ),
                ),
                (
                    "critical_water_level",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Критический уровень для оповещения, см",
                    ),
                ),
                (
                    "last_telemetry_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время последнего пинга от поста",
                    ),
                ),
            ],
            bases=("core.basehydrofacility",),
        ),
        migrations.CreateModel(
            name="InspectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(verbose_name="Дата проведения осмотра"),
                ),
                (
                    "inspector_name",
                    models.CharField(max_length=255, verbose_name="ФИО инспектора"),
                ),
                (
                    "has_cracks",
                    models.BooleanField(
                        default=False, verbose_name="Наличие трещин/разрушений бетона"
                    ),
                ),
                (
                    "crack_criticality",
                    models.IntegerField(
                        choices=[
                            (0, "Нет"),
                            (1, "Микротрещины"),
                            (2, "Средние дефекты"),
                            (3, "Сквозные/Критические трещины"),
                        ],
                        default=0,
                        verbose_name="Тяжесть трещин",
                    ),
                ),
                (
                    "is_silted",
                    models.BooleanField(
                        default=False, verbose_name="Заилено/заращено ли русло"
                    ),
                ),
                (
                    "siltation_percentage",
                    models.FloatField(
                        default=0.0, verbose_name="Процент заиления русла (0.0 - 100.0)"
                    ),
                ),
                (
                    "has_filtration",
                    models.BooleanField(
                        default=False,
                        verbose_name="Наличие опасной фильтрации/утечки воды",
                    ),
                ),
                (
                    "has_deformation",
                    models.BooleanField(
                        default=False,
                        verbose_name="Наличие просадок, сдвигов плит, пучения грунта",
                    ),
                ),
                (
                    "equipment_malfunction",
                    models.BooleanField(
                        default=False,
                        verbose_name="Поломка затворов/насосов/механической части",
                    ),
                ),
                (
                    "detected_wear_override",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Фактический износ, зафиксированный на месте, %",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_logs",
                        to="core.basehydrofacility",
                        verbose_name="Объект",
                    ),
                ),
            ],
        ),
    ]
