# Generated by Django 5.2.11 on 2026-06-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repair_status",
                    models.CharField(
                        choices=[
                            ("normal", "Норма"),
                            ("inspection_required", "Требуется осмотр"),
                            ("repair_required", "Требуется ремонт"),
                            ("critical", "Критическое состояние"),
                        ],
                        default="normal",
                        max_length=30,
                        verbose_name="Статус необходимости ремонта",
                    ),
                ),
                (
                    "inspection_interval_days",
                    models.IntegerField(
                        default=365, verbose_name="Рекомендуемая частота осмотра в днях"
                    ),
                ),
                (
                    "next_inspection_date",
                    models.DateField(verbose_name="Дедлайн следующего осмотра"),
                ),
                (
                    "calculated_importance",
                    models.CharField(
                        choices=[
                            ("low", "Низкая"),
                            ("medium", "Средняя"),
                            ("high", "Высокая"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="Класс критичности/важности объекта",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего расчета модели"
                    ),
                ),
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="core.basehydrofacility",
                        verbose_name="Объект",
                    ),
                ),
            ],
        ),
    ]
