# Generated by Django 5.2.15 on 2026-06-26 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0003_basehydrofacility_has_pressure_front'),
        ('monitoring', '0003_inspectionlog_crack_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityanalytics',
            name='condition_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Непрерывный индекс состояния (0–100 / отношение F к R)'),
        ),
        migrations.AddField(
            model_name='facilityanalytics',
            name='last_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_analytics', to='monitoring.inspectionlog', verbose_name='Осмотр-основание текущего статуса'),
        ),
        migrations.AddField(
            model_name='facilityanalytics',
            name='repair_status_reason',
            field=models.JSONField(blank=True, null=True, verbose_name='Обоснование статуса: сработавшие факторы (п. 4.3.3)'),
        ),
        migrations.AddField(
            model_name='facilityanalytics',
            name='requires_verification',
            field=models.BooleanField(default=False, verbose_name='Требует проверки (нет данных / устарели / противоречивы)'),
        ),
        migrations.AddField(
            model_name='facilityanalytics',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней смены статуса'),
        ),
        migrations.CreateModel(
            name='SafetyCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(choices=[('filtration_rate', 'Расход фильтрации'), ('deformation_value', 'Смещение/просадка'), ('crack_width', 'Раскрытие трещины'), ('water_level', 'Уровень воды')], max_length=30, verbose_name='Контролируемый показатель')),
                ('direction', models.CharField(choices=[('higher_worse', 'Опасность растёт с увеличением значения (K1 ≤ K2)'), ('lower_worse', 'Опасность растёт с уменьшением значения (K1 ≥ K2)')], default='higher_worse', max_length=20, verbose_name='Направление опасности')),
                ('unit', models.CharField(max_length=30, verbose_name='Единица измерения')),
                ('k1_warning_value', models.FloatField(verbose_name='K1 — предупреждающее значение (→ ремонт)')),
                ('k2_critical_value', models.FloatField(verbose_name='K2 — предельное значение (→ критическое)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий критерий')),
                ('valid_from', models.DateField(verbose_name='Дата уточнения критерия (п. 4.3.3)')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_criteria', to='core.basehydrofacility', verbose_name='Объект')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('direction', 'higher_worse'), ('k1_warning_value__lte', models.F('k2_critical_value'))), models.Q(('direction', 'lower_worse'), ('k1_warning_value__gte', models.F('k2_critical_value'))), _connector='OR'), name='safetycriterion_k1_before_k2')],
            },
        ),
    ]
