# Generated by Django 5.2.11 on 2026-06-25 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OSMImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="osm", max_length=20, verbose_name="Источник"
                    ),
                ),
                (
                    "osm_type",
                    models.CharField(max_length=10, verbose_name="Тип OSM-элемента"),
                ),
                ("osm_id", models.BigIntegerField(verbose_name="OSM ID")),
                (
                    "facility_type",
                    models.CharField(max_length=30, verbose_name="Тип сооружения"),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        verbose_name="ID локального объекта"
                    ),
                ),
                (
                    "first_imported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Первый импорт"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обнаружение"
                    ),
                ),
                ("raw_tags", models.JSONField(default=dict, verbose_name="OSM-теги")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип локальной модели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись импорта OSM",
                "verbose_name_plural": "Записи импорта OSM",
                "indexes": [
                    models.Index(
                        fields=["source", "osm_type", "osm_id"],
                        name="osm_import__source_5a01ce_idx",
                    ),
                    models.Index(
                        fields=["facility_type"], name="osm_import__facilit_eb3621_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "osm_type", "osm_id"),
                        name="unique_osm_import_source_type_id",
                    )
                ],
            },
        ),
    ]
